Revert osm_db_files.c: Fix bad free in osm_db_delete
as this causes memory leak.

commit 41233823fe4a9e0460451a217dc3303b2bcacf69
Author: Honggang Li <honli@redhat.com>
Date:   Mon Aug 6 14:23:42 2018 +0800

    osm_db_files.c: Fix bad free in osm_db_delete

    This issue was found by Coverity.

    Error: BAD_FREE (CWE-763): [#def64]
    opensm-3.3.20/opensm/osm_db_pack.c:260: array_free: "osm_db_delete" frees array "guid_str".
    opensm-3.3.20/opensm/osm_db_files.c:665:4: freed_arg: "free" frees parameter "p_key".

    All uses of p_key parameter were allocated on stack rather than heap.

    Signed-off-by: Honggang Li <honli@redhat.com>
    Signed-off-by: Hal Rosenstock <hal@mellanox.com>

Signed-off-by: Hal Rosenstock <hal@mellanox.com>