libvendor/osm_vendor_ibumad.c: Fix type of array passed to umad_get_ca_portguids in libibumad
Fixes GCC warning:
osm_vendor_ibumad.c: In function ‘osm_vendor_open_port’:
osm_vendor_ibumad.c:745:56: error: passing argument 2 of ‘umad_get_ca_portguids’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   if ((r = umad_get_ca_portguids(p_vend->ca_names[ca], portguids,
                                                        ^~~~~~~~~

Second argument to umad_get_ca_portguids was changed from uint64_t * to __be64 * in rdma-core by:
96db7b90 (Bart Van Assche 2017-03-10 14:52:27 -0800 178) int umad_get_ca_portguids(const char *ca_name, __be64 *portguids, int max);

Note that this change causes similar warning when OpenSM is built
with older libibumad rather than the other way around as it was
prior to this patch.
osm_vendor_ibumad.c: In function 'osm_vendor_open_port':
osm_vendor_ibumad.c:747: warning: passing argument 2 of 'umad_get_ca_portguids' from incompatible pointer type
./../../libibumad/include/infiniband/umad.h:166: note: expected 'uint64_t *' but argument is of type '__be64 *'

Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>
Signed-off-by: Hal Rosenstock <hal@mellanox.com>