osm_[congestion_control perfmgr].c: Fix signed vs unsigned comparison
Change loop indexes to unsigned where required to avoid
 these type of GCC warnings:
osm_congestion_control.c: In function ‘cc_setup_mad_data’:
osm_congestion_control.c:193:16: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
  for (i = 0; i < p_cc->cc_tbl_mads; i++) {
                ^

Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>
Signed-off-by: Hal Rosenstock <hal@mellanox.com>